# Generated by Django 2.0.5 on 2018-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
